# Generated by Django 5.2.1 on 2025-06-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="items_image",
            field=models.CharField(
                default="https://www.thefuzzyduck.co.uk/wp-content/uploads/2024/05/image-coming-soon-placeholder-01-660x660.png",
                max_length=500,
            ),
        ),
    ]
